version: 2

sources:
  - name: raw_data
    database: FINDATA_PROJECT
    schema: RAW
    tables:
      - name: COMPANY_PROFILES
        description: Raw customer profile data from FMP api
        columns:
          - name: symbol
            description: unique stock ticker symbol
            tests:
              - not_null
              - unique
          - name: company_name
            description: unique stock ticker symbol
            tests:
              - not_null
      - name: daily_stock_prices
        description: Raw historical record of daily stock prices for certain companies from FMP api
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - date
                - symbol
        columns:
          - name: date
            description: historical date of stock prices
            tests:
              - not_null
          - name: symbol
            description: stock ticker symbol
            tests:
              - not_null
